name: YouTube Shorts Local AI Automation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

jobs:
  run-automation:
    runs-on: ubuntu-latest

    env:
      CLIENT_SECRET_JSON: ${{ secrets.CLIENT_SECRET_JSON }}
      TOKEN_JSON: ${{ secrets.TOKEN_JSON }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Save YouTube secrets
      run: |
        echo "$CLIENT_SECRET_JSON" > client_secret.json
        echo "$TOKEN_JSON" > token.json

    - name: Run Local AI Automation
      run: python scripts/full_automation_local.py

    - name: Clean up temp files
      run: |
        rm -f client_secret.json
        rm -f token.json
        rm -rf assets/images/*
        rm -rf assets/voices/*
        rm -rf assets/videos/*
