name: build
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */5 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg
          python -m pip install --upgrade pip
          pip install --prefer-binary -r requirements.txt
      - name: Write secrets to files
        env:
          TOKEN_JSON: ${{ secrets.TOKEN_JSON }}
          CLIENT_SECRET_JSON: ${{ secrets.CLIENT_SECRET_JSON }}
        run: |
          echo "$TOKEN_JSON" > token.json
          echo "$CLIENT_SECRET_JSON" > client_secret.json
      - name: Run script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python main.py
